name: Ant Media Server Automation Actions

on: [push]

#on:
#  schedule:
#    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC

jobs:
  mongodb_install_ubuntu_20_04:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up MongoDB
        run: |
          curl --progress-bar -o ams_community.zip -L "$(curl -s -H "Accept: application/vnd.github+json" https://api.github.com/repos/ant-media/Ant-Media-Server/releases | jq -r '.[1].assets[0].browser_download_url')"
          wget https://raw.githubusercontent.com/ant-media/Scripts/master/install_ant-media-server.sh
          bash ./install_ant-media-server.sh -i ams_community.zip
          sleep 30
          bash ./upgrade.sh
